// A customer reports a problem. PURE -- nothing here reads or writes state.
//
// THE WORLD CONTROLLER DECIDES THE EVENT HAPPENED. No model is asked whether a customer has a
// problem, which customer it is, what is wrong, or how badly. All of that is a seeded draw over
// the company's own categories, so the business event exists as structured facts first.
//
// THE EMAIL IS RENDERED FROM THOSE FACTS, deterministically, from fragment pools -- the same
// approach src/seed/activity.ts already takes and says why: "Prose is composed from fragment
// pools rather than generated by an LLM. That keeps the manifest byte-stable for free, keeps
// spend at zero, and is adequate for short, ordinary language." A customer's two-line problem
// report is exactly that case. Replay therefore never asks a model to reproduce anything, and
// the rendered mail is persisted anyway so a later renderer change cannot rewrite history.

import { SUPPORT_CATEGORIES, type SupportSeverity } from "../charter/charter.ts";
import { messageIdFor } from "../seed/gmailMime.ts";
// From ../seed/addresses.ts, which imports nothing, so spelling one address costs this module no
// dependencies at all.
import { customerDomain, localPart } from "../seed/addresses.ts";
import type { Rng } from "../seed/rng.ts";
import type { CrmContact, CrmWorld } from "../support/customers.ts";
import { allLivingCompanies, type LivingCrmState } from "./livingCrmState.ts";
import { INCIDENT_CAUSED_SHARE } from "./productIncident.ts";
import { openRequestCountFor, type LivingInboundEmail, type LivingSupportState } from "./livingSupportState.ts";

/**
 * Meridian's shared support inbox.
 *
 * The company's support policy establishes it as a fact about how support works -- "Support has
 * been run from shared judgement and a shared inbox since we started" -- so the address is a
 * derived detail rather than an invention. It uses the internal reserved domain for the same
 * reason every other synthetic address does: the sandbox domain policy forbids asserting any
 * registrable domain as a mail origin. Every address in this repository therefore ends in the
 * reserved `.invalid` TLD (RFC 2606), which can never be registered and never resolves.
 */
export const SUPPORT_INBOX = "support@meridianworks.invalid";

/**
 * How many requests one account may have open at once.
 *
 * Not a business rule, a realism guard: without it the seeded draw will eventually pile six open
 * requests on one account while eighty-four others have none, which reads as a generator artefact
 * rather than as a support queue. Two is enough to allow a genuinely troubled account.
 */
export const MAX_OPEN_PER_ACCOUNT = 2;

export interface SupportRequestPlan {
  companyId: string;
  companyName: string;
  contactId: string;
  contactName: string;
  contactEmail: string;
  category: string;
  severity: SupportSeverity;
  problem: string;
  subject: string;
  body: string;
  /**
   * The incident that caused this request, when one did. Null for an independent customer issue.
   *
   * HIDDEN WORLD CONTROLLER TRUTH. It sits beside `problem`, `category` and `severity`, which are
   * already the Controller's structured statement of what went wrong and are already withheld from
   * whatever answers a request: an injected processor is handed the rendered email, the policy and
   * the account, and none of these. So this field is not a new class of
   * secret in a new place; it is one more fact in the same place, under the same boundary.
   *
   * It is the ONLY link between a customer's email and the fault behind it, and it exists so the
   * simulation can be audited -- "did this request come from the recurring-jobs incident" has to be
   * answerable without guessing from the category. tests/productIncidents.test.ts asserts it cannot
   * reach the ThreadMessage, the agent's prompt, a decision-record request or the customer's reply.
   */
  causedByIncidentId: string | null;
}

/**
 * An active incident, as the support planner needs to see it.
 *
 * A NARROW VIEW, not the stored incident. The planner needs the capability (which fixes the symptom
 * the customer reports), the affected accounts, and the id to record the attribution. It does not
 * need, and is not given, the owner, the planned resolution instant or the rest of the record.
 */
export interface CausingIncident {
  incidentId: string;
  capability: string;
  affectedCompanyIds: readonly string[];
}

// --- the fragment pools --------------------------------------------------------------
//
// One subject, one problem sentence and one body opener per category. Each is written in a
// customer's voice: what they see, what it is stopping, no diagnosis and no Meridian vocabulary.
// A customer does not know the category name, so none of these text fragments contains it.

interface CategoryCopy {
  subject: readonly string[];
  /** The factual problem, which is the structured fact the support employee works from. */
  problem: readonly string[];
  /** What the customer adds after the problem. Kept short, as a real first email is. */
  detail: readonly string[];
}

const COPY: Readonly<Record<string, CategoryCopy>> = Object.freeze({
  dispatch_outage: {
    subject: ["Dispatch board not loading", "Crews cannot be dispatched this morning"],
    problem: [
      "The dispatch board will not load, so no crew can be assigned.",
      "Dispatchers cannot assign work; the board is empty for every depot.",
    ],
    detail: [
      "Our dispatchers have been on the phone to crews since seven. Anything you can tell us would help.",
      "We have around forty jobs that should already be out. This is stopping work.",
    ],
  },
  data_import: {
    subject: ["Import finished but rows are missing", "Job import looks incomplete"],
    problem: [
      "An import reported success but fewer jobs are present than the file contained.",
      "The imported job list is short against the file we uploaded.",
    ],
    detail: [
      "The file had more rows than we can see in the product. We have kept the original if you need it.",
      "We noticed because the counts did not match what our scheduler expected.",
    ],
  },
  recurring_jobs: {
    subject: ["Recurring jobs not generating", "Maintenance visits missing from the schedule"],
    problem: [
      "A recurring job template is not generating its upcoming visits.",
      "Scheduled repeat visits have stopped appearing after a template change.",
    ],
    detail: [
      "We changed the pattern last week and nothing new has appeared since.",
      "Our quarterly maintenance work is the part affected.",
    ],
  },
  exception_queue: {
    subject: ["Exception queue count looks wrong", "Exception queue showing stale jobs"],
    problem: [
      "The exception queue count does not match the jobs actually listed in it.",
      "Jobs that were covered are still sitting in the exception queue.",
    ],
    detail: [
      "It seems to correct itself if we reload, but the first number is wrong.",
      "It is making it hard to tell what genuinely still needs covering.",
    ],
  },
  board_divergence: {
    subject: ["Planned schedule and board disagree", "Board does not match the plan"],
    problem: [
      "The planned schedule and the day-of board show different work for the same crews.",
      "A crew's board shows jobs the plan does not, and the plan shows jobs the board does not.",
    ],
    detail: [
      "We are using both views and cannot tell which one the crews should trust.",
      "It started after we moved a few jobs between depots.",
    ],
  },
  seat_change: {
    subject: ["Need to reassign a user", "Adding a dispatcher to our account"],
    problem: [
      "A user needs adding or reassigning within the seats the account already pays for.",
      "A dispatcher has left and their seat needs moving to a new starter.",
    ],
    detail: [
      "Happy for you to make the change; tell me if you need anything from me first.",
      "No rush on this one, but it would help before the end of the week.",
    ],
  },
  configuration_help: {
    subject: ["Help setting up a new depot", "Question about job type configuration"],
    problem: [
      "The customer needs help configuring their own account settings.",
      "A configuration change is needed and the customer is unsure which setting controls it.",
    ],
    detail: [
      "I can see the settings but I am not certain which one does what I want.",
      "We are adding a region and I would rather ask than get it wrong.",
    ],
  },
  data_export: {
    subject: ["Export of our job history", "Can we get our data out"],
    problem: [
      "The customer is requesting an export of their own data in a supported format.",
      "The customer wants their job history exported for their own reporting.",
    ],
    detail: [
      "Our finance team wants to reconcile it against our own records.",
      "A spreadsheet would be fine if that is easiest.",
    ],
  },
});

/** Every category the copy pools cover. Asserted against the charter's set in tests. */
export const COPY_CATEGORIES: readonly string[] = Object.freeze(Object.keys(COPY));

/**
 * Accounts that can raise a support request right now.
 *
 * CUSTOMERS ONLY. The frozen world supports this directly: `status` is customer, prospect or
 * churned, and support is for people who have the product. A prospect's questions go to the AE
 * working the deal, which is the sales pipeline, not the support inbox. Nothing in the frozen
 * data shows a prospect contacting support.
 *
 * Read from the RESOLVED view, so a prospect that a living closed-won deal converted becomes
 * eligible naturally, with no list of frozen customers anywhere.
 */
export function eligibleSupportAccounts(
  world: CrmWorld,
  crm: LivingCrmState | null,
  support: LivingSupportState | null,
): { companyId: string; companyName: string }[] {
  const withContact = new Set(world.contacts.map((c) => c.companyMeridianId));
  return allLivingCompanies(world, crm)
    .filter((c) => c.status === "customer")
    .filter((c) => withContact.has(c.meridianId))
    .filter((c) => openRequestCountFor(support, c.meridianId) < MAX_OPEN_PER_ACCOUNT)
    .sort((a, b) => (a.meridianId < b.meridianId ? -1 : a.meridianId > b.meridianId ? 1 : 0))
    .map((c) => ({ companyId: c.meridianId, companyName: c.name }));
}

/**
 * Who at the account writes in.
 *
 * Weighted toward the people who actually use the product day to day: a dispatcher or ops
 * manager reports a broken board, not the CFO. Drawn from the account's real contacts, so the
 * sender is always somebody the CRM already knows.
 */
function pickContact(world: CrmWorld, companyId: string, rng: Rng): CrmContact {
  const theirs = world.contacts
    .filter((c) => c.companyMeridianId === companyId)
    .sort((a, b) => (a.meridianId < b.meridianId ? -1 : 1));
  if (theirs.length === 0) throw new Error(`no contact at ${companyId} to raise a support request`);
  const weight = (role: string): number =>
    role === "user" ? 5 : role === "champion" ? 4 : role === "it" ? 2 : 1;
  const pairs = theirs.map((c) => [c, weight(c.role)] as const);
  return rng.weighted(pairs);
}

/**
 * Which active incident, if any, causes this request.
 *
 * NO DRAW IS TAKEN WHEN THERE IS NOTHING TO DECIDE. If no incident is active, or none of the
 * affected accounts is currently eligible to write in, this returns null having consumed no Rng at
 * all -- so a world with no active incident produces exactly the stream it produced before
 * incidents existed. That is the same rule selectFamily states for itself ("Not drawing when there
 * is no choice matters for replay"), applied here for the same reason.
 *
 * ELIGIBILITY FIRST, PROBABILITY SECOND. The affected set is intersected with the accounts that
 * could legitimately raise a request right now -- current customers, with a contact, under the
 * open-request cap -- BEFORE the coin is tossed. An incident never reaches past the existing rules
 * to make an ineligible account write in.
 */
function pickCausingIncident(
  incidents: readonly CausingIncident[],
  eligible: readonly { companyId: string }[],
  rng: Rng,
): { incident: CausingIncident; accounts: { companyId: string }[] } | null {
  if (incidents.length === 0) return null;

  const eligibleIds = new Set(eligible.map((a) => a.companyId));
  const candidates = incidents
    .map((incident) => ({
      incident,
      accounts: eligible.filter((a) => incident.affectedCompanyIds.includes(a.companyId)),
    }))
    .filter((c) => c.accounts.length > 0 && c.incident.affectedCompanyIds.some((id) => eligibleIds.has(id)));
  if (candidates.length === 0) return null;

  // The coin. Half the time an eligible affected customer reports the fault; half the time this
  // request is an ordinary independent issue that happens to arrive during an incident.
  if (!rng.bool(INCIDENT_CAUSED_SHARE)) return null;

  // More than one capability broken at once is possible but rare. Uniform when it happens: ranking
  // them would assert that one fault is reported sooner than another, which nothing measures.
  return candidates.length === 1 ? candidates[0] : candidates[rng.int(0, candidates.length - 1)];
}

/**
 * Plan one inbound support request, or null when no account can raise one.
 *
 * Draw order is fixed: the causal coin (only when an incident could have caused this), then
 * account, contact, category (skipped when an incident forces it), then the three copy choices.
 * Reordering any of these re-rolls every value after it.
 *
 * TWO ORIGINS, ONE PLANNER. A request is either an independent customer issue or a report of an
 * active fault, and both come out of this function as the same shape. Splitting them into two
 * planners would have duplicated the account rules, the contact weighting and the copy pools --
 * and the whole point is that a caused request is an ORDINARY support email whose subject happens
 * to be determined by something real.
 */
export function planSupportRequest(
  world: CrmWorld,
  crm: LivingCrmState | null,
  support: LivingSupportState | null,
  rng: Rng,
  /** Incidents active at this instant. Empty, or omitted, means every request is independent. */
  activeIncidents: readonly CausingIncident[] = [],
): SupportRequestPlan | null {
  const accounts = eligibleSupportAccounts(world, crm, support);
  if (accounts.length === 0) return null;

  const caused = pickCausingIncident(activeIncidents, accounts, rng);

  // A caused request comes from an AFFECTED account; an independent one from any eligible account.
  const pool = caused ? caused.accounts : accounts;
  const account = pool.length === 1 ? pool[0] : pool[rng.int(0, pool.length - 1)];
  const resolved = accounts.find((a) => a.companyId === account.companyId)!;
  const contact = pickContact(world, resolved.companyId, rng);

  // Category frequency follows severity: most inbound mail is a question or a degraded
  // account, and a full dispatch outage is rare. Weighted so the inbox reads like a support
  // queue rather than a uniform sample of the taxonomy.
  //
  // FORCED, AND NO DRAW TAKEN, when an incident caused this. The customer is reporting the fault
  // that is actually happening, so the category IS the broken capability -- which is what makes the
  // visible email symptom match the incident family by construction rather than by assertion. A
  // draw here would let a dispatch outage surface as a data-export request.
  const category = caused
    ? caused.incident.capability
    : rng.weighted([
        ["configuration_help", 6],
        ["seat_change", 5],
        ["data_export", 4],
        ["data_import", 4],
        ["recurring_jobs", 3],
        ["exception_queue", 3],
        ["board_divergence", 2],
        ["dispatch_outage", 1],
      ] as const);
  const severity = SUPPORT_CATEGORIES[category];
  const copy = COPY[category];
  if (!copy) {
    // Only reachable if a capability were added without copy. Refused rather than rendering an
    // empty email, because a customer report with no prose is not a customer report.
    throw new Error(`no customer-voice copy for support category ${category}`);
  }

  const subject = rng.pick(copy.subject);
  const problem = rng.pick(copy.problem);
  const detail = rng.pick(copy.detail);

  const company = world.companies.find((c) => c.meridianId === resolved.companyId)!;
  const contactName = `${contact.firstName} ${contact.lastName}`;

  return {
    companyId: resolved.companyId,
    companyName: resolved.companyName,
    contactId: contact.meridianId,
    contactName,
    // Derived the way the frozen corpus derives it, never taken from the CRM's .com address.
    contactEmail: `${localPart(contactName)}@${customerDomain(company.domain)}`,
    category,
    severity,
    problem,
    subject,
    body: [
      "Hello,",
      problem.replace(/^The customer /, "We ").replace(/^An import/, "An import"),
      detail,
      "Thanks,",
      `${contact.firstName} ${contact.lastName}`,
      `${contact.jobTitle}, ${resolved.companyName}`,
    ].join("\n\n"),
    // Recorded, never rendered. Nothing above reads it; the prose comes entirely from the copy
    // pools, which contain no incident vocabulary because a customer does not know there is one.
    causedByIncidentId: caused ? caused.incident.incidentId : null,
  };
}

/**
 * The email as the mailbox holds it.
 *
 * Separated from planning so the rendering is a pure function of the plan plus the request id
 * and the receipt time -- which is what makes the persisted mail reproducible from the recorded
 * facts. The Message-ID comes from the frozen corpus's own helper, keyed on the request id
 * alone, so the same request always has the same message id from any call site.
 */
export function renderInboundEmail(
  plan: SupportRequestPlan,
  requestId: string,
  receivedAtMs: number,
  dateHeader: string,
): LivingInboundEmail {
  return {
    rfcMessageId: messageIdFor(requestId),
    from: { name: plan.contactName, email: plan.contactEmail },
    to: SUPPORT_INBOX,
    subject: plan.subject,
    dateHeader,
    body: plan.body,
  };
}
